name: push-to-s3
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo
jobs:
  push-to-s3:
      runs-on: ubuntu-latest
      steps:
        - name: checkout current repo
          uses: actions/checkout@v3
        - name: configure aws credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            role-to-assume: arn:aws:iam::275502406073:role/github-actions-oidc 
            role-duration-seconds: 900 # the ttl of the session, in seconds.
            aws-region: us-east-1 # use your region here.
        - name: Serverless deploy
          run: aws s3 sync resume/* s3://stavgold-resume/resume 
