
name: push-to-s3
run-name: Push content to S3 bucket
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo
jobs:
  push-to-s3:
      runs-on: ubuntu-latest
      steps:
        - name: checkout current repo
          uses: actions/checkout@v3
          with:
            path: resume
        - name: Get current date
          id: date
          run: echo "dateUpdated=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT 
        - name: Read data json
          id: file_data
          uses: juliangruber/read-file-action@v1
          with:
            path: resume/resume_data.json
        - name: Add date updated to resume data 
          id: data
          uses: actions/github-script@v6
          with:
            script: |
              var data = ${{ steps.file_data.outputs.content }}; 
              data.dateUpdated = "${{ steps.date.outputs.dateUpdated }}";
              return data;
        - name: run ejs
          uses: jaywcjlove/action-ejs@main
          with:
            template-file: resume/template.ejs 
            vars: |
              ${{ steps.data.outputs.result }}
            output: resume/resume.html
        - name: configure aws credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            role-to-assume: arn:aws:iam::275502406073:role/github-actions-oidc 
            role-duration-seconds: 900 # the ttl of the session, in seconds.
            aws-region: us-east-2 # use your region here.
        - name: Serverless deploy
          run: aws s3 sync resume s3://www.stav.gold/resume 


